### PR TITLE
Add branding to loader div (Ionide logo)

### PR DESCRIPTION
**Pull request by jeroldhaas**

### CODE REVIEW

**Comment by forki** [comment]
do you have a screenshot?

**Comment by forki** [comment]
nice

**Comment by jeroldhaas** [comment]
Perhaps some CSS3 effects would be nice touch-up (drop shadow + glow) but I'll look at that later. I'm just trying to get rid of the white box. :smile:

**Comment by Krzysztof-Cieslak** [comment]
Released in `1.0.2`

**Pull request merged**
